### ISSUE TITLE
Setup Instructions - no package install needed on JupyterHub

### ISSUE THREAD

**Issue by ilessing** [UCSBCarpentry/2022-11-8-ucsb-reproducible-pubs#2]
The instuctions at:
https://ucsbcarpentry.github.io/2022-11-8-ucsb-reproducible-pubs/setup.html

should be adjusted to indicate that the whole package install routine isn't needed if learner is working on the LSIT hosted JupyterHub environment.  

Package Install routine is only needed when learner is using stand alone RStudio on their own computer.

**Comment by ilessing** [comment]
in slack @kristi-sara said they would fix this.

**Comment by kristi-sara** [comment]
Working on it

**Comment by kristi-sara** [comment]
Does it look ok now?

**Comment by ilessing** [comment]
Yes. Looks good.
awsome.. done.
